apiVersion: apps/v1
kind: Deployment
metadata:
  name: tictactoe-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tictactoe-frontend
  template:
    metadata:
      labels:
        app: tictactoe-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: tictactoe-frontend
        image: antpass79/tictactoe-frontend
        env:
        - name: BACKEND_ENDPOINT
          value: http://13.80.107.201:8080/tictactoe/
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tictactoe-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: tictactoe-frontend